### ISSUE TITLE
Supported Country

### ISSUE THREAD

**Issue by amosayomide05** [Namelocms/SquidSMS#1]
Does it work for all countries phone number?

**Comment by Namelocms** [comment]
Hi @amosayomide05 !

The SMTP Library which this uses basically attaches the number to the beginning of the email addresses in the CARRIERS list, so
### **The code here will work with any number you enter, _BUT_ there are a few things to be aware of:**

#### Selected Carrier must cover phone number
- To send anything the carrier has to cover the recipients number, so if the number is from a country where one of the currently available carriers is not operating, it wont work
  - Currently only ATT, Verizon, TMobile, and Sprint are supported as carriers, if the recipient number is not covered by one of these then you will have to find the carrier that matches the recipient's number and add it to the CARRIERS list at line 12
#### Phone number must match 10-digit format, or change the source code
- The current code is setup to accept only 10-digit numbers, eg. 5551234567, where the first 3 are the area code and the last 7 are the actual number. If your recipient number uses a different format you will have to alter the code at line 131:
  - `if len(phone_number) == your_number_length:`
  - The number shouldn't include a country code, at least as far as I can gather from testing with numbers from the USA.

Let me know if there are any other questions, Hope this helps!
